  version: 1.0.{build}
  image: Visual Studio 2019

  before_build:
    - cmd: echo "Preparing for build..."

  after_build:
    - cmd: echo "Building completed."

  deploy:
    provider: GitHubPages
    branch: gh-pages 
    folder: dist 
    skip_cleanup: true 
    on:
      branch: master 
   
