version: 1.0.{build}
image: Visual Studio 2019

# Скрипты сборки
build_script:
  - npm install
  - npm run build

# Настройки развертывания
deploy:
  provider: GitHubPages
  repository: Elizabess/popovers
  branch: gh-pages
  folder: dist
  # Убедитесь, что у вас есть токен доступа к GitHub
  access_token: $GITHUB_TOKEN
