version: 1.0.{build}
image: Visual Studio 2019

build:
  mode: script

script:
  - npm install
  - npm run build  # Замените на вашу команду сборки

deploy:
  provider: GitHubPages
  branch: gh-pages 
  folder: dist 
  skip_cleanup: true 
  on:
    branch: master