    version: 1.0.{build}
    image: Visual Studio 2019

    configuration:
      - Release

    build_script:
      - npm install
      - npm run build

    deploy:
      provider: GitHubPages
      github_repo: Elizabess/popovers
      on:
        branch: main
    
